apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager-namespace.yaml
commonLabels:
  app.kubernetes.io/component: operator
  app.kubernetes.io/instance: percona-server-mongodb-operator
  app.kubernetes.io/name: percona-server-mongodb-operator
  app.kubernetes.io/part-of: percona-server-mongodb-operator
images:
- name: psmdb-operator
  newName: tishina/percona-server-mongodb-operator
  newTag: main
