---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-account-percona-server-mongodb-operator
subjects:
  - kind: ServiceAccount
    name: percona-server-mongodb-operator
    namespace: "psmdb-operator"
roleRef:
  kind: ClusterRole
  name: percona-server-mongodb-operator
  apiGroup: rbac.authorization.k8s.io